# Generated by Django 4.2.4 on 2023-09-27 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reader.book')),
            ],
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morpheme', models.CharField(max_length=50)),
                ('page_index', models.IntegerField()),
                ('part_of_speech', models.CharField(max_length=25)),
                ('parse', models.JSONField(default={}, verbose_name='parse')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='reader.page')),
            ],
        ),
    ]
