# Generated by Django 4.2.4 on 2023-09-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpheme',
            name='parse',
            field=models.JSONField(default=dict, verbose_name='parse'),
        ),
    ]
