# Generated by Django 4.2.4 on 2023-09-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_morpheme_parse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morpheme',
            name='part_of_speech',
        ),
    ]
