# Generated by Django 4.2.4 on 2023-09-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_remove_morpheme_part_of_speech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='morpheme',
            options={'ordering': ['page_index']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['book', 'page_num']},
        ),
    ]
