# Generated by Django 4.2.4 on 2023-12-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_book_options_alter_morpheme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpheme',
            name='page_index',
            field=models.IntegerField(unique=True),
        ),
    ]
