# Generated by Django 4.2.4 on 2023-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_alter_morpheme_parse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpheme',
            name='page_index',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='morpheme',
            unique_together={('page', 'page_index')},
        ),
    ]
